### ISSUE TITLE
item监听为什么放在adapter中啊？

### ISSUE THREAD

**Issue by fuxuemingzhu** [laobie/NineGridImageView#1]
一般控件的监听不应该是类似 listview.setOnItemClickListener()么，是通过控件来设置item监听的。这个库是放在adapter中的，为什么这么做呢？

**Comment by laobie** [comment]
http://www.fuxuemingzhu.com/2016/03/08/Android-List-Recycler-NineGrid-Views-Using-3/

回复的说明在上文的评论里
