### ISSUE TITLE
是否支持动态删除？

### ISSUE THREAD

**Issue by ypf168326** [laobie/NineGridImageView#11]
您好，看了项目代码，好像没有动态删除功能，这个可否加上？

**Comment by laobie** [comment]
@ypf168326 其实你自己写上逻辑，然后更新数据，最后刷新下列表就可以的，这个改动不大的，属于需要开发者自己加的功能

**Comment by ypf168326** [comment]
恩，我后来自己实现了。

Jaeger <notifications@github.com>于2016年12月6日 周二11:06写道：

**Comment by laobie** [comment]
@ypf168326 ok，那我关闭 issue 了哈

**Comment by ypf168326** [comment]
恩，关闭吧
Jaeger <notifications@github.com>于2016年12月9日 周五11:14写道：
