### ISSUE TITLE
onItemImageClick返回的list

### ISSUE THREAD

**Issue by chenwulue** [laobie/NineGridImageView#13]
` protected void onItemImageClick(Context context, int index, List<String> list)`
这里的list，目前是返回了显示在屏幕上的list，不应该是原始list吗 
比如我的lis是12个元素，但是我默认只显示9个，点击之后才跳到新页面来显示所有的元素

或者说回调多一个参数呢，比如变成
`protected void onItemImageClick(Context context, int index, List<String> list,List<String> initList)`

**Comment by laobie** [comment]
@chenwulue 这应该是个 bug 明天修复一个，应该返回原始数据

**Comment by laobie** [comment]
@chenwulue 1.0.3 已经修复此问题
