### ISSUE TITLE
转场动画的实现

### ISSUE THREAD

**Issue by chenwulue** [laobie/NineGridImageView#14]
需要做点击图片查看详情的时候，有个放大缩小的功能，那就要获取到当前的ImageView，onItemImageClick能返回这个View吗

**Comment by laobie** [comment]
@chenwulue 需要回传给你当前 view 稍晚 我更新下加上这个

**Comment by laobie** [comment]
@chenwulue 
1.1.0 版本已经发布了，回传了 ImageView
