### ISSUE TITLE
断点调试，发现无法实现复用

### ISSUE THREAD

**Issue by androidXiaoHao** [laobie/NineGridImageView#17]
作者你好，在调试您的这个九宫格控件的时候遇到些问题。假设列表中第一个item中有一张图片，第二个item有三张图片。发现mImgDataList第一次为null，这个时候就可以添加imageview布局将图片显示上去，当显示第二个item时，按理说这个时候mImgDataList的size为1了，就应该走else语句了，去再new两个imageview即可。但是断点调试的结果是，显示第二个item的时候，走这个if-else语句时，mImgDataList仍为null。这样的话就相当于new三个imageview，无法重用。如下图
![quest](https://cloud.githubusercontent.com/assets/16314954/25037321/22cda198-212b-11e7-90bb-a85feaef625a.png)
希望作者能抽时间解答下，谢谢~

**Comment by laobie** [comment]
那你页面上显示了 4 个 ImageView，你的意思只要 new 3 个？

**Comment by androidXiaoHao** [comment]
假如说我的list列表就两项，两个item，第一个item显示一张图片，第二个item显示三张图片。那么第一次调用这个方法，发现mImgDataList为null，就new一个imageview出来。第二个item(三张图片)显示的时候，按理说这个时候不应该只需要再new两个imageview出来，复用原先new的那个布局。不知道我的理解对不对

**Comment by laobie** [comment]
建议看看 RecyclerView 或者 ListView 的复用机制再来探讨这个问题

**Comment by androidXiaoHao** [comment]
突然间好像明白了，这个复用机制是不是当前布局滑出去后（假如这个布局的item中图片为3张），后面布局进入时（进入的item中图片为5张），那么后面进入的布局就可以复用之前滑出去的布局，并且只需要再new两个imageview即可？不知道说的对不对？

**Comment by laobie** [comment]
对了

**Comment by androidXiaoHao** [comment]
多谢大牛解答

**Comment by laobie** [comment]
不客气
