### ISSUE TITLE
当图片没有的时候出现错乱

### ISSUE THREAD

**Issue by sduqlsc** [laobie/NineGridImageView#2]
考虑当图片没有的时候，recyclerView会出现错乱，这个算是一个改进建议吧~作为ViewGroup，在bind的时候因为是动态添加子view的，首先调用removeAllViews或者判断一下list的size是否妥当写些？

**Comment by laobie** [comment]
我回去看看，我项目中处理的是没图片是直接gone了

**Comment by laobie** [comment]
@sduqlsc 谢谢反馈，这确实是一个bug

**Comment by laobie** [comment]
谢谢你的反馈，1.0.1中修复了这个bug，现在图片为0或者是null，那么该控件就会不显示了。

还有你说的动态添加的话，你setImageData的话应该和你要得效果一样的，不影响吧，或者就这个你再联系下我，我看看怎么回事

**Comment by sduqlsc** [comment]
好的，没问题！
