### ISSUE TITLE
有三张图片的时候，能显示一行吗？

### ISSUE THREAD

**Issue by hudan2714** [laobie/NineGridImageView#26]
现在有三张图片，显示成二行。能显示成一行吗？需要 怎样修改呢？

**Comment by laobie** [comment]
![image](https://user-images.githubusercontent.com/7184320/30537140-2ab1bc36-9c2e-11e7-90bf-b90e9a0fb206.png)

默认的 `STYLE_GRID` 就是三张显示一行的

**Comment by hudan2714** [comment]
我用的是STYLE_Full，要的效果是，1，2，3，4，6，8，9张图时都占满屏幕。。目前是，三张图的时候，会有两行，

**Comment by laobie** [comment]
3张一行怎么占满屏幕？

**Comment by hudan2714** [comment]
看来是我没描述清楚啊，6张图不是两行三张占满屏幕，3张就一行占满屏幕，看了你style_full是第一行2张第二行1张，这样显示的，这个问题，我判断每个条目的图片数量，然后显示不同的style方式解决了。。

还想请教一个问题是，现在显示的图片都好像是正方形的？请问题，能修改图片的宽高不一样吗？比如：一张图片的时候，宽为屏幕宽度，高为宽的3/4，这样能显示吗？我这样修改好像没有效果
@overide
 protected ImageView generateImageView(Context context) {
  GridImageView imageView = new GridImageView(context);
            imageView.setAdjustViewBounds(true);
            if (size == 1) {//一张图片
                int screenWidth = ScreenUtils.getScreenWidth();
                int height = screenWidth * 3 / 4;
                imageView.setMaxWidth(screenWidth);
                imageView.setMaxHeight(height);
           }
  imageView.setScaleType(ImageView.ScaleType.FIT_XY);
            return imageView;
}
还请指教，麻烦了。。。

在线等，还请指教可以修改的思路，因为最近需要使用。。。谢谢了！
