### ISSUE TITLE
singleSize的大小最好有个判断

### ISSUE THREAD

**Issue by yanglfree** [laobie/NineGridImageView#3]
singleImgSize的大小最好有个判断
当xml中定义的大小超过屏幕尺寸的时候，用屏幕尺寸大小
不然的话xml中定义非常大的时候，显示是不合理的

**Comment by laobie** [comment]
好的，确实是个bug，我下个版本改掉

**Comment by laobie** [comment]
你好，感谢你的反馈，1.0.1中已经修复了这个bug
