### ISSUE TITLE
我放在recyclerview里面, 不知道为什么一直在刷新

### ISSUE THREAD

**Issue by Deepblue1996** [laobie/NineGridImageView#34]
![image](https://user-images.githubusercontent.com/16926380/32047072-795bc7e8-ba77-11e7-8c7d-78f4de8adfe5.png)

**Comment by laobie** [comment]
嗯？解决了么？

**Comment by Deepblue1996** [comment]
Picasso取消memoryPolicy(NO_CACHE, NO_STORE)即可解决

**Comment by laobie** [comment]
哦哦 好的

**Comment by Deepblue1996** [comment]
我有个建议,希望官方增加对单张图片指定高度,宽度自适应控件宽度
