### ISSUE TITLE
Glide加载不出来图片???

### ISSUE THREAD

**Issue by jwzywanasnli** [laobie/NineGridImageView#36]
一直显示占位图，退出再进去才正常显示。弱弱的问下，这个项目作者还更新么。看到好多问题都很久了。。。  (ಥ﹏ಥ)

**Comment by laobie** [comment]
Gilde 加载不出来图片应该是自己相关参数设置的问题，项目目前没啥需要更新的，暂时就不怎么维护了

**Comment by yanxinmiao** [comment]
@laobie Glide加载图片这么多人都有问题， 不会都是参数配置的问题吧 ？ 不再解决了吗 ？？

**Comment by laobie** [comment]
@yanxinmiao 代码开源的，都来提 issue ，提个 pr 这么难么？伸手还这么理直气壮，惯坏了吧

**Comment by yungelee** [comment]
> 一直显示占位图，退出再进去才正常显示。弱弱的问下，这个项目作者还更新么。看到好多问题都很久了。。。 (ಥ﹏ಥ)
我也遇到了网络加载不出来的问题，各种Glide策略设置了效果还是很差有时候一直显示占位图，两三张图的九宫格问题不大，但是6张以上经常就一直显示占位图。

**Comment by sunshinecf** [comment]
我的也加载不出来
