### ISSUE TITLE
能否不控制图片9张的上限

### ISSUE THREAD

**Issue by mxn21** [laobie/NineGridImageView#4]
能否不限制图片上限，我在NineGridImageView中把下面的注释了就好了，因为如果做一个时间轴的demo，不能保证每一个item最多9张图，或者超过了9张提供接口控制。
if (lists.size() > 9) {
           lists = lists.subList(0, 9);
        }
另外图片的点击背景效果最好可以提供接口修改。

**Comment by laobie** [comment]
点击效果的其实你看一下源码 就是我自己自定义了一个ImageView的，你可以子定义一个ImageView，写你自己的点击效果的，在adapter的一个方法里面可以实现的，最大图片限制的问题，我待会更新一个版本，提供方法设置

**Comment by laobie** [comment]
1.0.1 版本已经更新了，可以设置最大图片数，如果不想限制，最大图片数设置为0或者小于0就行了
