### ISSUE TITLE
在特殊情况图片循环被加载。

### ISSUE THREAD

**Issue by 272152441** [laobie/NineGridImageView#7]
使用的时候，在三星note4手机，展示6张图片。其中有2张图片会重复加载，图片加载用imageloader。现象是，图片被加载出来就重新再次加载。发生的概率比较小。怀疑是图片展示的回调接口重复调用。

**Comment by laobie** [comment]
按道理应该不会重复调用的，要重复的也不能是6张图中的两张，最好有详细点的代码
