### ISSUE TITLE
使用fresco加载图片非常卡顿

### ISSUE THREAD

**Issue by henry-newbie** [laobie/NineGridImageView#8]
我把picasso替换为fresco之后，listview在滚动的时候出现明显卡顿，暂时还没有找到原因

**Comment by laobie** [comment]
可能是 fresco 的配置不正确，包括缓存、滑动时不加载图片之类的，我公司用的 picasso 没问题的

**Comment by henry-newbie** [comment]
嗯嗯，应该是fresco没用好，谢谢

**Comment by laobie** [comment]
@henry-newbie 那我关掉 issue 了哈
