### ISSUE TITLE
большая первая картинка

### ISSUE THREAD

**Issue by sviter-pro** [laobie/NineGridImageView#9]
Сделайте что бы когда картинка одна, то она была по центру и большая

**Comment by laobie** [comment]
> Make that whenever one picture, she was in the middle and larger.

This is the result of a Google translation.  I can't understand, please explain the issue in English. Thank you.

**Comment by sviter-pro** [comment]
сделайте так тобы если картинка одна, то она была по центру и большая

**Comment by sviter-pro** [comment]
To do so if the picture is one, it was in the center and a large

**Comment by laobie** [comment]
`app:singleImgSize="120dp" or nineGridImageView.setSingleImgSize(int singleImgSize)`

set `singleImgSize` a big value (2000dp?), it may looks like below:

![image](https://cloud.githubusercontent.com/assets/7184320/20618419/e2b60696-b329-11e6-934c-9f3476720d96.png)

**Comment by laobie** [comment]
@sviter-pro

**Comment by sviter-pro** [comment]
Thank you ... and can be more than nine images display?

**Comment by laobie** [comment]
@sviter-pro 
`app:maxSize="9" or nineGridImageView.setMaxSize(int maxSize);`

**Comment by laobie** [comment]
@sviter-pro 
Here is result.　
![image](https://cloud.githubusercontent.com/assets/7184320/20618633/2efecf5a-b32b-11e6-8680-ebc4cef0c779.png)

**Comment by sviter-pro** [comment]
Thank you
